### ISSUE TITLE
Experimental DTS and Multi-entrypoint builds

### ISSUE THREAD

**Issue by jacob-alford** [egoist/tsup#1046]
I really like the option to use @microsoft/api-extractor for DTS types.  However, it doesn't work for all cases.  It seems that it's currently only built for single entrypoint builds, see this section here:

https://api-extractor.com/pages/setup/configure_rollup/#an-important-limitation

And another thing, it doesn't seem to be copying the emitted dts files into the dist directory, even though it seems that it should be.

I also wanted to comment, Tsup is an incredible library and it's made building esm/cjs libs a breeze.  Thank you very much for your work 🙏🏻

**Comment by moltar** [comment]
> And another thing, it doesn't seem to be copying the emitted dts files into the dist directory, even though it seems that it should be.

Yeah, I think there's a bug somewhere.

```
> tsup --config="tsup.config.json"

Analysis will use the bundled TypeScript version 5.0.4
*** The target project appears to use TypeScript 5.2.2 which is newer than the bundled compiler engine; consider upgrading API Extractor.
Writing package typings: .../packages/foo/lib/_tsup-dts-rollup.d.ts
Analysis will use the bundled TypeScript version 5.0.4
*** The target project appears to use TypeScript 5.2.2 which is newer than the bundled compiler engine; consider upgrading API Extractor.
Writing package typings: .../packages/projen-typescript-package-build/lib/_tsup-dts-rollup.d.mts
```

```
❯ tree lib
lib
├── index.js
├── index.js.map
├── index.mjs
├── index.mjs.map
└── src

2 directories, 4 files
```

The declarations (`_tsup-dts-rollup.d.{ts,mts}`) are missing.

**Comment by ocavue** [comment]
Could you share a minimal reproduction? Thanks!

**Comment by louwers** [comment]
```
git clone https://github.com/sinclairzx81/typebox.git
cd typebox
npm install --save-dev tsup @microsoft/api-extractor
npx tsup src/index.ts --experimental-dts
CLI Building entry: src/index.ts
CLI Using tsconfig: tsconfig.json
CLI tsup v8.3.5
TSC Build start
TSC Failed to emit declaration files.

/Users/bart/src/typebox/example/annotation/annotation.ts (131,59): Property 'Deref' does not exist on type 'JavaScriptTypeBuilder'. Did you mean 'Ref'?
/Users/bart/src/typebox/node_modules/typescript/lib/lib.es5.d.ts (1579,11): Type parameter 'P' has a circular constraint.
/Users/bart/src/typebox/node_modules/typescript/lib/lib.es5.d.ts (1586,11): Type parameter 'P' has a circular constraint.
/Users/bart/src/typebox/node_modules/typescript/lib/lib.es5.d.ts (1600,11): Type parameter 'P' has a circular constraint.
Error: TypeScript compilation failed
    at emitDtsFiles (/Users/bart/src/typebox/node_modules/tsup/dist/index.js:1131:11)
    at emit (/Users/bart/src/typebox/node_modules/tsup/dist/index.js:1166:23)
    at runTypeScriptCompiler (/Users/bart/src/typebox/node_modules/tsup/dist/index.js:1177:21)
    at experimentalDtsTask (/Users/bart/src/typebox/node_modules/tsup/dist/index.js:1504:29)
    at dtsTask (/Users/bart/src/typebox/node_modules/tsup/dist/index.js:1514:17)
    at /Users/bart/src/typebox/node_modules/tsup/dist/index.js:1698:28
    at async Promise.all (index 0)
    at async build (/Users/bart/src/typebox/node_modules/tsup/dist/index.js:1490:3)
    at async CAC.<anonymous> (/Users/bart/src/typebox/node_modules/tsup/dist/chunk-SNM7IVOJ.js:143:5)
    at async main (/Users/bart/src/typebox/node_modules/tsup/dist/chunk-SNM7IVOJ.js:148:3)
TSC Build error
DTS Build start
Error: Unexpected internal error: dts exports is not define
    at runDtsRollup (/Users/bart/src/typebox/node_modules/tsup/dist/index.js:1373:13)
    at experimentalDtsTask (/Users/bart/src/typebox/node_modules/tsup/dist/index.js:1505:19)
    at dtsTask (/Users/bart/src/typebox/node_modules/tsup/dist/index.js:1514:17)
    at /Users/bart/src/typebox/node_modules/tsup/dist/index.js:1698:28
    at async Promise.all (index 0)
    at async build (/Users/bart/src/typebox/node_modules/tsup/dist/index.js:1490:3)
    at async CAC.<anonymous> (/Users/bart/src/typebox/node_modules/tsup/dist/chunk-SNM7IVOJ.js:143:5)
    at async main (/Users/bart/src/typebox/node_modules/tsup/dist/chunk-SNM7IVOJ.js:148:3)
DTS Build error
CLI Target: es2020
CJS Build start
CJS dist/index.js 121.69 KB
CJS ⚡️ Build success in 37ms
```
