### ISSUE TITLE
tsup is not working with `npx`

### ISSUE THREAD

**Issue by himself65** [egoist/tsup#1184]
```
npx tsup x.js --dts --format esm
⠙
Error: Cannot find module 'typescript'
Require stack:
- /Users/himself65/.npm/_npx/7d72304e626f8399/node_modules/tsup/dist/index.js
- /Users/himself65/.npm/_npx/7d72304e626f8399/node_modules/tsup/dist/chunk-CDF4QN4B.js
- /Users/himself65/.npm/_npx/7d72304e626f8399/node_modules/tsup/dist/cli-default.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/Users/himself65/.npm/_npx/7d72304e626f8399/node_modules/tsup/dist/index.js:1021:19)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
```

**Comment by Sunny-117** [comment]
```shell
npm i -g typescript
npx tsup 
```

**Comment by watfordsuzy** [comment]
That doesn't appear to solve it:
```sh
scratch/connector on  spike/tsup [$?] is 📦 1.0.0 via ⬢ v20.11.0 on 🐳 v27.5.1 using ☁️ Sandbox  
➜ npx tsup                   
Error: Cannot find module 'typescript'
Require stack:
- /Users/watfordsuzy/.npm/_npx/7d72304e626f8399/node_modules/tsup/dist/index.js
- /Users/watfordsuzy/.npm/_npx/7d72304e626f8399/node_modules/tsup/dist/chunk-R3P2Q4VY.js
- /Users/watfordsuzy/.npm/_npx/7d72304e626f8399/node_modules/tsup/dist/cli-default.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/watfordsuzy/.npm/_npx/7d72304e626f8399/node_modules/tsup/dist/index.js:1023:19)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)

scratch/connector on  spike/tsup [$?] is 📦 1.0.0 via ⬢ v20.11.0 on 🐳 v27.5.1 using ☁️ Sandbox 
➜ npm i -g typescript        

added 1 package in 239ms

scratch/connector on  spike/tsup [$?] is 📦 1.0.0 via ⬢ v20.11.0 on 🐳 v27.5.1 using ☁️ Sandbox 
➜ npx tsup           
Error: Cannot find module 'typescript'
Require stack:
...
```

**Comment by Sunny-117** [comment]
This error occurs because tsup lists TypeScript as a peer dependency, meaning it expects TypeScript to be installed in your project. When using npx tsup, if TypeScript is not installed in your project, tsup cannot find it.
Solution:
Install TypeScript in your project:
```bash
npm install typescript --save-dev
```
After installation, `npx tsup x.js --dts --format esm` should work correctly.
Note that globally installed TypeScript won't be found by require('typescript'), as Node.js module resolution doesn't automatically look in global packages.
