### ISSUE TITLE
`injectStyle` function with `dts: true` results in `DataCloneError`

### ISSUE THREAD

**Issue by arielweinberger** [egoist/tsup#1194]
When using `injectStyle` with a function and having `dts: true` example:

```ts
// tsup.config.ts
import { defineConfig, Options } from "tsup-async-inject-style";

export default defineConfig((options: Options) => {
  return {
    entry: ["src/**/*.ts", "src/**/*.tsx"],
    format: ["esm", "cjs"],
    dts: true,
    minify: false,
    external: ["react"],
    splitting: false,
    clean: true,
    sourcemap: true,
    injectStyle: (css) => {
      return `console.log()`
    },
    ...options,
  };
});
```

I get the following error:

```
DataCloneError: (css) => {
      return `console.log()`;
    } could not be cloned.
    at new DOMException (node:internal/per_context/domexception:53:5)
    at Worker.postMessage (node:internal/worker:378:5)
    at /Users/arielweinberger/Development/copilotkit/CopilotKit/CopilotKit/node_modules/.pnpm/tsup-async-inject-style@0.0.1_@swc+core@1.5.28_jiti@1.21.6_postcss@8.4.40_typescript@5.5.4_yaml@2.5.0/node_modules/tsup-async-inject-style/dist/index.js:1521:22
    at new Promise (<anonymous>)
    at dtsTask (/Users/arielweinberger/Development/copilotkit/CopilotKit/CopilotKit/node_modules/.pnpm/tsup-async-inject-style@0.0.1_@swc+core@1.5.28_jiti@1.21.6_postcss@8.4.40_typescript@5.5.4_yaml@2.5.0/node_modules/tsup-async-inject-style/dist/index.js:1515:19)
    at /Users/arielweinberger/Development/copilotkit/CopilotKit/CopilotKit/node_modules/.pnpm/tsup-async-inject-style@0.0.1_@swc+core@1.5.28_jiti@1.21.6_postcss@8.4.40_typescript@5.5.4_yaml@2.5.0/node_modules/tsup-async-inject-style/dist/index.js:1700:28
    at async Promise.all (index 0)
    at async build (/Users/arielweinberger/Development/copilotkit/CopilotKit/CopilotKit/node_modules/.pnpm/tsup-async-inject-style@0.0.1_@swc+core@1.5.28_jiti@1.21.6_postcss@8.4.40_typescript@5.5.4_yaml@2.5.0/node_modules/tsup-async-inject-style/dist/index.js:1492:3)
    at async CAC.<anonymous> (/Users/arielweinberger/Development/copilotkit/CopilotKit/CopilotKit/node_modules/.pnpm/tsup-async-inject-style@0.0.1_@swc+core@1.5.28_jiti@1.21.6_postcss@8.4.40_typescript@5.5.4_yaml@2.5.0/node_modules/tsup-async-inject-style/dist/chunk-777RIKDU.js:143:5)
    at async main (/Users/arielweinberger/Development/copilotkit/CopilotKit/CopilotKit/node_modules/.pnpm/tsup-async-inject-style@0.0.1_@swc+core@1.5.28_jiti@1.21.6_postcss@8.4.40_typescript@5.5.4_yaml@2.5.0/node_modules/tsup-async-inject-style/dist/chunk-777RIKDU.js:148:3)
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/egoist) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/egoist/tsup/issues/1194">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/egoist/tsup/issues/1194/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/egoist/tsup/issues/1194/pledge.svg">
</picture>
</a>

**Comment by arielweinberger** [comment]
My PR #1193 fixes this one as well.
