### ISSUE TITLE
Silent flag?

### ISSUE THREAD

**Issue by OmgImAlexis** [egoist/tsup#142]
Any chance on a silent flag being added to silence the logging?

For example.

```
> rm -rf dist && tsup src/index.ts --format esm,cjs,iife --legacy-output --dts

 CLI  Using tsconfig: /Users/xo/.npm/_cacache/tmp/git-clone-77b5acfa/tsconfig.json
 CLI  Target: es2020
 ESM  Build start
 CJS  Build start
 IIFE  Build start
 ESM  Build success in 9ms
 CJS  Build success in 57ms
 IIFE  Build success in 56ms
 DTS  Build start
 DTS  Build success in 1300ms
```

**Comment by OmgImAlexis** [comment]
PING: @egoist 
Also any chance on the opposite to show more logging when an error happens.

For example this doesn't give me much to go off of.
```
Using tsconfig: /tmp/tsconfig.json
Illegal reassignment to import 'commonjsHelpers'
dist/index.js - 862 kB
Done in 15355ms
```

**Comment by OmgImAlexis** [comment]
Another example is when using the `minify` flag. From that I have no clue how to fix the issue.

```
Error parsing: undefined:31:4
SyntaxError: Unexpected token, expected ";" (31:4)
    at unexpected (/Users/xo/code/unraid/logger/node_modules/sucrase/dist/parser/traverser/util.js:83:15)
    at semicolon (/Users/xo/code/unraid/logger/node_modules/sucrase/dist/parser/traverser/util.js:61:5)
    at parseStatementContent (/Users/xo/code/unraid/logger/node_modules/sucrase/dist/parser/traverser/statement.js:230:21)
    at parseStatement (/Users/xo/code/unraid/logger/node_modules/sucrase/dist/parser/traverser/statement.js:108:3)
    at parseBlockBody (/Users/xo/code/unraid/logger/node_modules/sucrase/dist/parser/traverser/statement.js:510:5)
    at parseBlock (/Users/xo/code/unraid/logger/node_modules/sucrase/dist/parser/traverser/statement.js:499:3)
    at parseFunctionBody (/Users/xo/code/unraid/logger/node_modules/sucrase/dist/parser/traverser/expression.js:930:27)
    at parseFunctionBodyAndFinish (/Users/xo/code/unraid/logger/node_modules/sucrase/dist/parser/traverser/expression.js:920:5)
    at parseFunction (/Users/xo/code/unraid/logger/node_modules/sucrase/dist/parser/traverser/statement.js:602:42)
    at parseFunctionExpression (/Users/xo/code/unraid/logger/node_modules/sucrase/dist/parser/traverser/expression.js:597:28)
```

**Comment by egoist** [comment]
> Error parsing: undefined:31:4

we can fix this, it seems we didn't get the filename properly

**Comment by PabloSzx** [comment]
@egoist I guess this issue should be closed, It was implemented here: https://github.com/egoist/tsup/pull/285
