### ISSUE TITLE
when running via npx it uses the wrong path

### ISSUE THREAD

**Issue by OmgImAlexis** [egoist/tsup#185]
```
npx tsup ./src/index.ts --format esm,cjs,iife --dts --minify
```

Even after installing `typescript` it wouldn't solve the issue, adding tsup to the current project and then trying with the local version fixed the issue.

```
Error: Cannot find module 'typescript'
Require stack:
- /Users/xo/.npm/_npx/96410/lib/node_modules/tsup/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.js
- /Users/xo/.npm/_npx/96410/lib/node_modules/tsup/dist/rollup.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/xo/.npm/_npx/96410/lib/node_modules/tsup/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.js:6:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
Emitted 'error' event on process instance at:
    at emitUnhandledRejectionOrErr (internal/event_target.js:543:11)
    at MessagePort.[nodejs.internal.kHybridDispatch] (internal/event_target.js:358:9)
    at MessagePort.exports.emitMessage (internal/per_context/messageport.js:18:26) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/xo/.npm/_npx/96410/lib/node_modules/tsup/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.js',
    '/Users/xo/.npm/_npx/96410/lib/node_modules/tsup/dist/rollup.js'
  ]
}
```

**Comment by egoist** [comment]
`rollup-plugin-dts` (which is a dependency of tsup) and `typescript` have to be installed in the same project, it's better to install tsup in the local project instead of using `npx`.

**Comment by OmgImAlexis** [comment]
Problem is I tend to use npx even if I have the dep installed as it’s meant to fall back the main advantage of this is not needing to worry if it’s Linux or windows. The command just works where as with windows at times we’ve hit slash issues in the scripts.

Is there any way to fix this?

**Comment by egoist** [comment]
but the error log shows it's trying to use the one installed by `npx` (`/Users/xo/.npm/_npx/96410/lib/node_modules/tsup`) instead of the one in your project.

**Comment by OmgImAlexis** [comment]
npx is meant to fall back to the local copy in node_modules/.bin so maybe this is a npx bug?

**Comment by unlight** [comment]
Can confirm the issue with npx, install `tsup` locally will solve the issue.
Flag `--no-save` can be used (`npm i tsup --no-save` on CI/CD) to not modify `package.json`

**Comment by egoist** [comment]
So basically, you have to install tsup locally in order to use `--dts` flag. If not please provide a repo so I can take a look.
