### ISSUE TITLE
help: how to bundle .svelte & ts files in the same repo

### ISSUE THREAD

**Issue by alexanderniebuhr** [egoist/tsup#299]
Hey there, I am trying to bundle normal ts files used in node & svelte files in the same repo.
It works, however declaration files do not get generated. I narrowed it down to some settings in my tsconfig, but setting the `types` field to svelte breaks.
Currently getting.. do you have help how to set this up correctly?
 ```
DTS  Build error
TypeError: Cannot destructure property 'column' of 'locate(...)' as it is undefined.
    at Module.addLocationToLogProps (C:\Users\Alexander\Documents\projects\svelteuse\router\node_modules\rollup\dist\shared\rollup.js:10295:15)
    at Module.error (C:\Users\Alexander\Documents\projects\svelteuse\router\node_modules\rollup\dist\shared\rollup.js:9764:14)
    at Module.getVariableForExportName (C:\Users\Alexander\Documents\projects\svelteuse\router\node_modules\rollup\dist\shared\rollup.js:9928:29)
    at Module.includeAllExports (C:\Users\Alexander\Documents\projects\svelteuse\router\node_modules\rollup\dist\shared\rollup.js:10000:35)
    at Graph.includeStatements (C:\Users\Alexander\Documents\projects\svelteuse\router\node_modules\rollup\dist\shared\rollup.js:19405:24)
    at Graph.build (C:\Users\Alexander\Documents\projects\svelteuse\router\node_modules\rollup\dist\shared\rollup.js:19339:14)
    at async rollupInternal (C:\Users\Alexander\Documents\projects\svelteuse\router\node_modules\rollup\dist\shared\rollup.js:20297:9)
    at async runRollup (C:\Users\Alexander\Documents\projects\svelteuse\router\node_modules\tsup\dist\rollup.js:6090:20)
    at async startRollup (C:\Users\Alexander\Documents\projects\svelteuse\router\node_modules\tsup\dist\rollup.js:6124:5)
```

**Comment by egoist** [comment]
svelte + dts support is not tested yet, it would be useful if you can provide a repro,

**Comment by alexanderniebuhr** [comment]
https://github.com/svelteuse/router

**Comment by alexanderniebuhr** [comment]
I tried to add `node` here too, but then it throws another error
https://github.com/svelteuse/router/blob/ec80f1c69a277a8c486cf478b2886df69ff86fc7/tsconfig.json#L9-L12
