### ISSUE TITLE
Weird type check error

### ISSUE THREAD

**Issue by yingpengsha** [egoist/tsup#357]
## Reproduction

[tsup-demo](https://www.github.com/yingpengsha/tsup-demo)

## Development environment

- Window10
- node v16.4.1
- pnpm v6.9.1

## Log

```bash
$ pnpm dev

> tsup-demo@1.0.0 dev D:\code\tsup-demo
> tsup index.ts --dts

 CLI  Building entry: index.ts
 CLI  Using tsconfig: D:\code\tsup-demo\tsconfig.json
 CLI  tsup v4.12.5
 CLI  Target: node12
 CJS  Build start
 CJS  Build success in 134ms
 DTS  Build start
index.ts(4,5): error TS2322: Type '{ name: string; transformIndexHtml: { enforce: "pre"; transform(html: string): { html: string; tags: { tag: string; attrs: { type: string; }; }[]; }; }; }' is not assignable to type 'Plugin'.  Object literal may only specify known properties, and 'name' does not exist in type 'Plugin'.

 DTS  Build error
Error: Failed to compile. Check the logs above.
    at error (D:\code\tsup-demo\node_modules\.pnpm\rollup@2.53.2\node_modules\rollup\dist\shared\rollup.js:151:30)
    at throwPluginError (D:\code\tsup-demo\node_modules\.pnpm\rollup@2.53.2\node_modules\rollup\dist\shared\rollup.js:19316:12)
    at Object.error (D:\code\tsup-demo\node_modules\.pnpm\rollup@2.53.2\node_modules\rollup\dist\shared\rollup.js:19968:20)
    at Object.error (D:\code\tsup-demo\node_modules\.pnpm\rollup@2.53.2\node_modules\rollup\dist\shared\rollup.js:19492:38)
    at Object.transform (D:\code\tsup-demo\node_modules\.pnpm\tsup@4.12.5_typescript@4.3.5\node_modules\tsup\dist\rollup.js:6014:20)
    at D:\code\tsup-demo\node_modules\.pnpm\rollup@2.53.2\node_modules\rollup\dist\shared\rollup.js:20173:25     
 ERROR  Command failed with exit code 1.
```

**Comment by yingpengsha** [comment]
Vite's Plugin type clearly has a name key, but it still reports an error when generating dts.🤨

**Comment by egoist** [comment]
there's some problem with rollup-plugin-dts when using pnpm

**Comment by egoist** [comment]
that should be fixed now.

**Comment by ckken** [comment]
same here `"tsup": "^6.1.2"`
