### ISSUE TITLE
--dts-resolve doesn't fully resolve imported type

### ISSUE THREAD

**Issue by OmgImAlexis** [egoist/tsup#367]
Seems `--dts-resolve` doesn't take into account that request's types should be coming from `./node_modules/@types/request/index` and not `./node_modules/request/index.js`.

```console
npm i request
npm i -D @types/request
```

```ts
import { Options } from 'request';

export const opts: Partial<Options> = {};
```

```console
 CLI  Building entry: ./src/file.ts
 CLI  Using tsconfig: /Users/xo/code/OmgImAlexis/snoostream/tsconfig.json
 CLI  tsup v4.12.5
 CLI  Target: node12
 CJS  Build start
 CJS  Build success in 20ms
 DTS  Build start
 DTS  Build error
Error: 'Options' is not exported by node_modules/request/index.js, imported by src/file.ts
    at error (/Users/xo/code/OmgImAlexis/snoostream/node_modules/rollup/dist/shared/rollup.js:151:30)
    at Module.error (/Users/xo/code/OmgImAlexis/snoostream/node_modules/rollup/dist/shared/rollup.js:10020:16)
    at Module.traceVariable (/Users/xo/code/OmgImAlexis/snoostream/node_modules/rollup/dist/shared/rollup.js:10405:29)
    at ModuleScope.findVariable (/Users/xo/code/OmgImAlexis/snoostream/node_modules/rollup/dist/shared/rollup.js:9176:39)
    at FunctionScope.findVariable (/Users/xo/code/OmgImAlexis/snoostream/node_modules/rollup/dist/shared/rollup.js:3636:38)
    at Identifier.bind (/Users/xo/code/OmgImAlexis/snoostream/node_modules/rollup/dist/shared/rollup.js:4573:40)
    at AssignmentPattern.bind (/Users/xo/code/OmgImAlexis/snoostream/node_modules/rollup/dist/shared/rollup.js:2884:23)
    at FunctionDeclaration.bind (/Users/xo/code/OmgImAlexis/snoostream/node_modules/rollup/dist/shared/rollup.js:2880:31)
    at Program.bind (/Users/xo/code/OmgImAlexis/snoostream/node_modules/rollup/dist/shared/rollup.js:2880:31)
    at Module.bindReferences (/Users/xo/code/OmgImAlexis/snoostream/node_modules/rollup/dist/shared/rollup.js:10016:18)
```

**Comment by OmgImAlexis** [comment]
@egoist any idea where this fix would need to be added?

I manually edited `./node_modules/request/package.json` and added a `types` field that points to `./node_modules/@types/request/index.d.ts` and it builds fine.

**Comment by OmgImAlexis** [comment]
Here's an example of the workaround. I'm using `patch-package` to apply this diff on post install.

https://github.com/OmgImAlexis/snoo-wrapped/commit/43e2fa7be241c337f29ceac039c22f2f57cfc4e9

**Comment by OmgImAlexis** [comment]
@egoist any chance you could look into this when you've got a moment?

**Comment by egoist** [comment]
I have fixed the issue that caused this (https://github.com/egoist/tsup/releases/tag/v5.7.1), but `@types/request` still can't be bundled because it's using `import x = require()`.

btw I think `node-fetch` already ships types so you don't need to use `@types/node-fetch`
