### ISSUE TITLE
DTS error with `composite`

### ISSUE THREAD

**Issue by Xenfo** [egoist/tsup#571]
Repo: https://github.com/flux-ui/flux-ui/tree/feat/checkbox-variants

Error:
```
src/index.ts(1,15): error TS6307: File '/home/xenfo/Desktop/Projects/flux-ui/packages/checkbox/src/checkbox.tsx' is not listed within the file list of project ''. Projects must list all files or use an 'include' pattern.

[CHECKBOX] DTS Build error
Error: Failed to compile. Check the logs above.
    at error (/home/xenfo/Desktop/Projects/flux-ui/node_modules/rollup/dist/shared/rollup.js:160:30)
    at throwPluginError (/home/xenfo/Desktop/Projects/flux-ui/node_modules/rollup/dist/shared/rollup.js:21828:12)
    at Object.error (/home/xenfo/Desktop/Projects/flux-ui/node_modules/rollup/dist/shared/rollup.js:22548:20)
    at Object.error (/home/xenfo/Desktop/Projects/flux-ui/node_modules/rollup/dist/shared/rollup.js:22005:42)
    at Object.transform (/home/xenfo/Desktop/Projects/flux-ui/node_modules/tsup/dist/rollup.js:8372:20)
    at /home/xenfo/Desktop/Projects/flux-ui/node_modules/rollup/dist/shared/rollup.js:22793:37
```

**Comment by ocavue** [comment]
https://github.com/Swatinem/rollup-plugin-dts/issues/127 

It seems that `rollup-plugin-dts`, which is used by `tsup` to output `.d.ts` files, doesn't support `composite` if we directly use it to bundle `.ts` files. 

It could support `composite` if we bundle `.d.ts` with `tsc` first and then use `rollup-plugin-dts` to bundle these `.d.ts` files. But that means extra work on `tsup` side.

**Comment by egoist** [comment]
Yeah  the workaround is to `tsc` to generate `.d.ts` instead, if you also want to bundle the generated types, you can also combine tsc with tsup:

```bash
# creates temp/*.d.ts
tsc --declarationDir temp --declaration --emitDeclarationOnly
# bundle temp/index.d.ts to dist/index.d.ts
tsup --entry.index temp/index.d.ts --dtsOnly
```

The `--entry` flag is added in v6.1.0, for older version you have to use `tsup.config.ts`:

```ts
export default defineConfig({
  entry: {
    index: './temp/index.d.ts'
  }
})
```

**Comment by toteto** [comment]
As workaround for now I have created separate `tsconfig.build.json` config that will be extending the original and will be used exclusively for builds with `tsup`. Now sure if this will backfire.

```json
// tsconfig.json
{
    "extends": "../../tsconfig.json",
    "compilerOptions": {
        "baseUrl": "./",
        "outDir": "./dist",
        "rootDir": "./src",
        "noEmit": false,
        "declarationMap": true,
        "declaration": true,
        "composite": true
    },
    "include": ["src"],
    "exclude": ["node_modules", "dist"]
}
```

```json
// tsconfig.build.json
{
    "extends": "./tsconfig.json",
    "compilerOptions": {
        "composite": false
    }
}
```

```ts
// tsup.config.ts
import { defineConfig } from 'tsup';

export default defineConfig({
        entry: ["src/index.ts", "src/childSum/index.ts"],
        tsconfig: 'tsconfig.build.json',
    });
```

Now you can run your `tsup` command, for me that is: `tsup --format cjs,esm --dts`

**Comment by segevfiner** [comment]
I can use:
```ts
// tsup.config.ts
import { defineConfig } from 'tsup';

export default defineConfig({
  dts: {
    compilerOptions: {
      composite: false,
    },
  },
  tsconfig: 'tsconfig.node.json'
});
```

To disable `composite` only for the d.ts build.

**Comment by okineadev** [comment]
> I can use:
> 
> ```ts
> // tsup.config.ts
> import { defineConfig } from 'tsup';
> 
> export default defineConfig({
>   dts: {
>     compilerOptions: {
>       composite: false,
>     },
>   },
>   tsconfig: 'tsconfig.node.json'
> });
> ```
> To disable `composite` only for the d.ts build.

Thank you very much! 🙌

This solved my problem
