### ISSUE TITLE
V6 breaks on fsevents

### ISSUE THREAD

**Issue by jlarmstrongiv** [egoist/tsup#636]
```
Error: s/tsup:turbo:build: ✘ [ERROR] Could not resolve "fsevents"
@configs/tsup:turbo:build: 
@configs/tsup:turbo:build:     ../../node_modules/rollup/dist/shared/rollup.js:629:114:
@configs/tsup:turbo:build:       629 │ ... => /*#__PURE__*/_interopNamespaceDefault(require('fsevents'))));
@configs/tsup:turbo:build:           ╵                                                      ~~~~~~~~~~
@configs/tsup:turbo:build: 
@configs/tsup:turbo:build:   You can mark the path "fsevents" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
@configs/tsup:turbo:build: 
@configs/tsup:turbo:build: IIFE Build failed
@configs/tsup:turbo:build: Error: Build failed with 1 error:
@configs/tsup:turbo:build: ../../node_modules/rollup/dist/shared/rollup.js:629:114: ERROR: Could not resolve "fsevents"
@configs/tsup:turbo:build:     at failureErrorWithLog (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/esbuild/lib/main.js:1603:15)
@configs/tsup:turbo:build:     at /home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/esbuild/lib/main.js:1249:28
@configs/tsup:turbo:build:     at runOnEndCallbacks (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/esbuild/lib/main.js:1034:63)
@configs/tsup:turbo:build:     at buildResponseToResult (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/esbuild/lib/main.js:1247:7)
@configs/tsup:turbo:build:     at /home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/esbuild/lib/main.js:1356:14
@configs/tsup:turbo:build:     at /home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/esbuild/lib/main.js:666:9
@configs/tsup:turbo:build:     at handleIncomingPacket (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/esbuild/lib/main.js:763:9)
@configs/tsup:turbo:build:     at Socket.readFromStdout (/home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/node_modules/esbuild/lib/main.js:632:7)
@configs/tsup:turbo:build:     at Socket.emit (node:events:390:28)
@configs/tsup:turbo:build:     at addChunk (node:internal/streams/readable:315:12)
@configs/tsup:turbo:build: npm ERR! Lifecycle script `turbo:build` failed with error: 
@configs/tsup:turbo:build: npm ERR! Error: command failed 
@configs/tsup:turbo:build: npm ERR!   in workspace: @configs/tsup@1.0.0 
@configs/tsup:turbo:build: npm ERR!   at location: /home/ubuntu/actions-runner/_work/turbo-monorepo/turbo-monorepo/configs/tsup 
@configs/tsup:turbo:build: ERROR: command finished with error: command (configs/tsup) npm run turbo:build exited (1)
```

**Comment by egoist** [comment]
Mind sharing your repo? Does it only break for `iife`?

**Comment by jlarmstrongiv** [comment]
@egoist invited to the repo 👍

**Comment by egoist** [comment]
tried your repo locally and it's working 😅

**Comment by jlarmstrongiv** [comment]
I just did that too 😂 it fails on the linux build server only, as "fsevents" is an optional dependency only installed on mac

**Comment by jlarmstrongiv** [comment]
Also, tsup [v5.12.9](https://github.com/egoist/tsup/releases/tag/v5.12.9) is missing `tsup-node`, so [v5.12.8](https://github.com/egoist/tsup/releases/tag/v5.12.8) is the last safe version.

**Comment by jlarmstrongiv** [comment]
Updated to 6.0.1, added `fsevents` to the externals array, as suggested by https://esbuild.github.io/api/#external, and cleared both local and global caches seemed to clean up other obscure errors 👍

**Comment by jlarmstrongiv** [comment]
Actually, the `IIFE` build still fails

**Comment by jlarmstrongiv** [comment]
@egoist to conclude, the problem is the [`fsevents`](https://www.npmjs.com/package/fsevents) package.  The `fsevents` package is used to listen to file events on MacOS, and cannot be installed on any other OS.  It is commonly used by packages like `chokidar`, `rollup`, `nextjs`, etc.

When building with tsup, it always expects to find and bundle `fsevents`.  However, this simply cannot happen on linux, as `fsevents` is not installed as an optional dependency.  Even if you specify `fsevents` as a `devDependency`, npm will throw errors about an unsupported platform / os.  

My workaround is to mock `fsevents` with a bash script using `package.json.scripts.postinstall`:

```bash
#!/usr/bin/env bash
set -euo pipefail

monorepo_path="path/to/your/monorepo"

fsevents_path="$monorepo_path/node_modules/fsevents"
if [[ "$(uname)" != "Darwin" ]] && [[ ! -d "$fsevents_path" ]]; then
    echo 'Mocking "fsevents"'
    mkdir -p "$fsevents_path"
    set -o noclobber
    echo '{"name":"fsevents","description":"MOCK FSEvents","main":"fsevents.js"}' >| "$fsevents_path/package.json"
    echo 'module.exports = {}' >| "$fsevents_path/fsevents.js"
fi
```

It’s not a pretty workaround, but it works.
