### ISSUE TITLE
Error: Dynamic require of "fs" is not supported

### ISSUE THREAD

**Issue by songwuk** [egoist/tsup#644]
hi
### When creating a plugin with tsup 

read file
`import fs from 'fs-extra'`

This error occurred after `npm run build `
`import { defineConfig } from 'tsup'`
`export default defineConfig({`
`  entry: ['src/index.ts'],`
`  splitting: true,`
`  loader: {`
`    '.ts': 'ts',`
`  },`
`  format: ['cjs', 'esm', 'iife'],`
`  sourcemap: false,`
`  clean: true,`
`  bundle: true,`
`})`

> errer 

`Error: Dynamic require of "fs" is not supported
    at file:///C:/Users/songwen/Desktop/bangdaocode/tsup-plugin-unocss/example/tsup.config.bundled_1654070874268.mjs:6:9
    at node_modules/_esbuild@0.14.42@esbuild/lib/main.js (file:///C:/Users/songwen/Desktop/bangdaocode/tsup-plugin-unocss/example/tsup.config.bundled_1654070874268.mjs:1735:15)
    at __require22 (file:///C:/Users/songwen/Desktop/bangdaocode/tsup-plugin-unocss/example/tsup.config.bundled_1654070874268.mjs:31:50)
    at file:///C:/Users/songwen/Desktop/bangdaocode/tsup-plugin-unocss/example/tsup.config.bundled_1654070874268.mjs:2321:23
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async extractResult (C:\Users\songwen\Desktop\bangdaocode\tsup-plugin-unocss\example\node_modules\tsup\node_modules\bundle-require\dist\index.cjs:185:13)
    at async loadTsupConfig (C:\Users\songwen\Desktop\bangdaocode\tsup-plugin-unocss\example\node_modules\tsup\dist\chunk-O4DTJHFR.js:63:20)
    at async build (C:\Users\songwen\Desktop\bangdaocode\tsup-plugin-unocss\example\node_modules\tsup\dist\index.js:2089:51)
    at async CAC.<anonymous> (C:\Users\songwen\Desktop\bangdaocode\tsup-plugin-unocss\example\node_modules\tsup\dist\chunk-UTAMPEAT.js:188:5)` 
 🙏

**Comment by ThaDaVos** [comment]
How did you solve this? Having the same issue with `fs`

**Comment by songwuk** [comment]
yes
maybe can use 

```ts
external: ['esbuild']
```

**Comment by sp00x** [comment]
For some reason I had the same because my tsconfig.json file included a "path" configuration like this (leftover from some other file I had copied): 

``` 
    "paths": {
      "types": [ "./types"],
      "*": [
        "./node_modules/*",
        "./src/typings/*"
      ]
    },
```
