### ISSUE TITLE
combining `watch` and `onSuccess` crashes

### ISSUE THREAD

**Issue by forivall** [egoist/tsup#679]
With an empty file `a.js`, I see the following
```
» npx tsup a.js --watch --onSuccess 'npm start'
CLI Building entry: a.js
CLI tsup v6.2.0
CLI Running in watch mode
CLI Target: node14
CJS Build start
CJS ⚡️ Build success in 36ms
CJS dist/a.js 0 B
CLI Watching for changes in "."
CLI Ignoring changes in "**/{.git,node_modules}/**" | "dist"

> tsup-sandbox@1.0.0 start
> node a.js

CLI Change detected: change a.js
CJS Build start
CJS ⚡️ Build success in 908ms
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: spawn pgrep EAGAIN
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -35,
  code: 'EAGAIN',
  syscall: 'spawn pgrep',
  path: 'pgrep',
  spawnargs: [ '-P', 71634 ]
}

Node.js v18.6.0
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0x140000021a0?)
	runtime/sema.go:56 +0x2c
sync.(*WaitGroup).Wait(0x140000b42d8)
	sync/waitgroup.go:136 +0x88
main.runService(0x1)
	github.com/evanw/esbuild/cmd/esbuild/service.go:177 +0x3e4
main.main()
	github.com/evanw/esbuild/cmd/esbuild/main.go:210 +0x1a8

goroutine 18 [chan receive]:
main.runService.func1()
	github.com/evanw/esbuild/cmd/esbuild/service.go:110 +0x50
created by main.runService
	github.com/evanw/esbuild/cmd/esbuild/service.go:108 +0x150

goroutine 19 [chan receive]:
main.(*serviceType).sendRequest(0x140000b42c0, {0x1031c70a0, 0x14000300b40})
	github.com/evanw/esbuild/cmd/esbuild/service.go:203 +0xec
main.runService.func2()
	github.com/evanw/esbuild/cmd/esbuild/service.go:132 +0x3c
created by main.runService
	github.com/evanw/esbuild/cmd/esbuild/service.go:129 +0x268
```

`package.json`
```json
{
  "name": "tsup-sandbox",
  "version": "1.0.0",
  "scripts": {
    "start": "node a.js"
  },
  "devDependencies": {
    "tsup": "^6.2.0"
  }
}
```

When `a.js` is a long running process, like a server, it's also left running.

**Comment by egoist** [comment]
Can't reproduce it using your example:
<img width="961" alt="CleanShot 2022-07-30 at 12 49 35@2x" src="https://user-images.githubusercontent.com/8784712/181873389-1582fb3d-47dc-4b12-8ce0-4a722b4a82f9.png">

can you reproduce it on https://stackblitz.com ?

**Comment by forivall** [comment]
I'll also note that i'm using node v16.15.0 . trying a repro on stackblitz now

**Comment by forivall** [comment]
The error is a little different on [stackblitz](https://stackblitz.com/edit/node-vmezm8?file=package.json), but I do still get an error:

Terminal 1:
```
~/projects/node-vmezm8
❯ npx tsup index.js --watch --onSuccess 'npm start'
CLI Building entry: index.js
CLI tsup v6.2.1
CLI Running in watch mode
CLI Target: node14
CJS Build start
CJS ⚡️ Build success in 161ms
CJS dist/index.js 69.00 B
CLI Watching for changes in "."
CLI Ignoring changes in "**/{.git,node_modules}/**" | "dist"
$ node index.js
Hello Node.js v16.14.2!
```

Terminal 2:
```
~/projects/node-vmezm8
❯ touch index.js
```

Back to Terminal 1:
```
CLI Change detected: change index.js
Error [ENOENT]: spawn ps ENOENT
    at get (https://node-vmezm8.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:292488)
    at getStackString (https://node-vmezm8.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:103704)
    at formatValue/</f< (https://node-vmezm8.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:99381)
    at formatValue/< (https://node-vmezm8.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:101164)
    at formatValue (https://node-vmezm8.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:103550)
    at inspect (https://node-vmezm8.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:6:92243)
    at _0x5e9d7f (https://node-vmezm8.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:15:147610)
    at _0x375210 (https://node-vmezm8.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:8:131367)
    at _0x371f77/_0x11674b< (https://node-vmezm8.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:15:139997)
    at _0x371f77 (https://node-vmezm8.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:15:140021)
    at _0x2e6f3b (https://node-vmezm8.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:8:260029)
    at <anonymous> (https://node-vmezm8.w-corp.staticblitz.com/blitz.1f021b18268b32e6c6b2095e039ac8c9f88b0d52.js:15:497971)
    at <anonymous> (<anonymous>) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ '-o', 'pid', '--no-headers', '--ppid', 13 ]
}

~/projects/node-vmezm8 26s
❯ fatal error: too many writes on closed pipe

goroutine 6 [running]:
runtime.throw({0x8bb4d, 0x1e})
        runtime/panic.go:1047 +0x3 fp=0x439ee0 sp=0x439eb8 pc=0x122b0003
os.sigpipe()
        runtime/os_js.go:143 +0x2 fp=0x439ef8 sp=0x439ee0 pc=0x139b0002
os.epipecheck(...)
        os/file_unix.go:195
os.(*File).Write(0x40c020, {0x478b40, 0x21, 0x40})
        os/file.go:183 +0x27 fp=0x439f80 sp=0x439ef8 pc=0x15d50027
main.runService.func1()
        github.com/evanw/esbuild/cmd/esbuild/service.go:114 +0xa fp=0x439fe0 sp=0x439f80 pc=0x1df1000a
runtime.goexit()
        runtime/asm_wasm.s:401 +0x1 fp=0x439fe8 sp=0x439fe0 pc=0x13ea0001
created by main.runService
        github.com/evanw/esbuild/cmd/esbuild/service.go:108 +0x13

goroutine 1 [semacquire]:
runtime.gopark(0xa0f80, 0x374e60, 0x12, 0x19, 0x4)
        runtime/proc.go:363 +0x27 fp=0x46dc38 sp=0x46dc10 pc=0x12520027
runtime.goparkunlock(...)
        runtime/proc.go:369
runtime.semacquire1(0x4443a0, 0x0, 0x1, 0x0)
        runtime/sema.go:150 +0x38 fp=0x46dc88 sp=0x46dc38 pc=0x12e50038
sync.runtime_Semacquire(0x4443a0)
        runtime/sema.go:62 +0x2 fp=0x46dcb0 sp=0x46dc88 pc=0x13b00002
sync.(*WaitGroup).Wait(0x444398)
        sync/waitgroup.go:139 +0x11 fp=0x46dcd8 sp=0x46dcb0 pc=0x14ab0011
main.runService(0x1)
        github.com/evanw/esbuild/cmd/esbuild/service.go:177 +0x40 fp=0x46ddd8 sp=0x46dcd8 pc=0x1dee0040
main.main()
        github.com/evanw/esbuild/cmd/esbuild/main.go:214 +0x8 fp=0x46df80 sp=0x46ddd8 pc=0x1de80008
runtime.main()
        runtime/proc.go:250 +0x35 fp=0x46dfe0 sp=0x46df80 pc=0x124d0035
runtime.goexit()
        runtime/asm_wasm.s:401 +0x1 fp=0x46dfe8 sp=0x46dfe0 pc=0x13ea0001

goroutine 2 [force gc (idle)]:
runtime.gopark(0xa0f80, 0x36e220, 0x11, 0x14, 0x1)
        runtime/proc.go:363 +0x27 fp=0x426fb8 sp=0x426f90 pc=0x12520027
runtime.goparkunlock(...)
        runtime/proc.go:369
runtime.forcegchelper()
        runtime/proc.go:302 +0x17 fp=0x426fe0 sp=0x426fb8 pc=0x12500017
runtime.goexit()
        runtime/asm_wasm.s:401 +0x1 fp=0x426fe8 sp=0x426fe0 pc=0x13ea0001
created by runtime.init.5
        runtime/proc.go:290 +0x2

goroutine 3 [GC sweep wait]:
runtime.gopark(0xa0f80, 0x36e520, 0xc, 0x14, 0x1)
        runtime/proc.go:363 +0x27 fp=0x4277a8 sp=0x427780 pc=0x12520027
runtime.goparkunlock(...)
        runtime/proc.go:369
runtime.bgsweep(0x42a000)
        runtime/mgcsweep.go:278 +0xf fp=0x4277d0 sp=0x4277a8 pc=0x117f000f
runtime.gcenable.func1()
        runtime/mgc.go:178 +0x2 fp=0x4277e0 sp=0x4277d0 pc=0x11030002
runtime.goexit()
        runtime/asm_wasm.s:401 +0x1 fp=0x4277e8 sp=0x4277e0 pc=0x13ea0001
created by runtime.gcenable
        runtime/mgc.go:178 +0x8

goroutine 4 [GC scavenge wait]:
runtime.gopark(0xa0f80, 0x36e720, 0xd, 0x14, 0x2)
        runtime/proc.go:363 +0x27 fp=0x427f80 sp=0x427f58 pc=0x12520027
runtime.goparkunlock(...)
        runtime/proc.go:369
runtime.(*scavengerState).park(0x36e720)
        runtime/mgcscavenge.go:389 +0xd fp=0x427fa8 sp=0x427f80 pc=0x1167000d
runtime.bgscavenge(0x42a000)
        runtime/mgcscavenge.go:617 +0x4 fp=0x427fd0 sp=0x427fa8 pc=0x116c0004
runtime.gcenable.func2()
        runtime/mgc.go:179 +0x2 fp=0x427fe0 sp=0x427fd0 pc=0x11020002
runtime.goexit()
        runtime/asm_wasm.s:401 +0x1 fp=0x427fe8 sp=0x427fe0 pc=0x13ea0001
created by runtime.gcenable
        runtime/mgc.go:179 +0xe

goroutine 5 [finalizer wait]:
runtime.gopark(0xa0f80, 0x38bcb0, 0x10, 0x14, 0x1)
        runtime/proc.go:363 +0x27 fp=0x426738 sp=0x426710 pc=0x12520027
runtime.goparkunlock(...)
        runtime/proc.go:369
runtime.runfinq()
        runtime/mfinal.go:180 +0x21 fp=0x4267e0 sp=0x426738 pc=0x10fa0021
runtime.goexit()
        runtime/asm_wasm.s:401 +0x1 fp=0x4267e8 sp=0x4267e0 pc=0x13ea0001
created by runtime.createfing
        runtime/mfinal.go:157 +0x5

goroutine 7 [waiting]:
runtime.gopark(0x0, 0x0, 0x0, 0x0, 0x1)
        runtime/proc.go:363 +0x27 fp=0x428f90 sp=0x428f68 pc=0x12520027
runtime.handleEvent()
        runtime/lock_js.go:257 +0x1b fp=0x428fe0 sp=0x428f90 pc=0x109a001b
runtime.goexit()
        runtime/asm_wasm.s:401 +0x1 fp=0x428fe8 sp=0x428fe0 pc=0x13ea0001
created by runtime.beforeIdle
        runtime/lock_js.go:207 +0x1a

goroutine 8 [chan receive]:
runtime.gopark(0xa0df8, 0x433138, 0xe, 0x17, 0x2)
        runtime/proc.go:363 +0x27 fp=0x438e80 sp=0x438e58 pc=0x12520027
runtime.chanrecv(0x4330e0, 0x438f70, 0x1)
        runtime/chan.go:583 +0x7c fp=0x438f08 sp=0x438e80 pc=0x1065007c
runtime.chanrecv1(0x4330e0, 0x438f70)
        runtime/chan.go:442 +0x2 fp=0x438f30 sp=0x438f08 pc=0x10630002
main.(*serviceType).sendRequest(0x444380, {0x3e380, 0x5e49c0})
        github.com/evanw/esbuild/cmd/esbuild/service.go:203 +0xe fp=0x438fa0 sp=0x438f30 pc=0x1df2000e
main.runService.func2()
        github.com/evanw/esbuild/cmd/esbuild/service.go:132 +0x3 fp=0x438fe0 sp=0x438fa0 pc=0x1df00003
runtime.goexit()
        runtime/asm_wasm.s:401 +0x1 fp=0x438fe8 sp=0x438fe0 pc=0x13ea0001
created by main.runService
        github.com/evanw/esbuild/cmd/esbuild/service.go:129 +0x28

```
