### ISSUE TITLE
Error: error occured in dts build

### ISSUE THREAD

**Issue by doerme** [egoist/tsup#790]
my tsup config:

```typescript
import { defineConfig } from 'tsup'

export default defineConfig({
    entry: ['src/index.ts'],
    splitting: false,
    sourcemap: true,
    clean: true,
    dts: true,
    outDir: 'dist',
    // skipNodeModulesBundle: true,
    platform: 'browser',
    // config: false
})
```

error msg detail:
```
Error: error occured in dts build
    at Worker.<anonymous> (/Users/liangxiaoming/Documents/baidu/yy-cocos-giftplayer/node_modules/.pnpm/tsup@6.3.0/node_modules/tsup/dist/index.js:2181:26)
    at Worker.emit (node:events:527:28)
    at MessagePort.<anonymous> (node:internal/worker:232:53)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:643:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
Error: Failed to compile. Check the logs above.
    at error (/Users/liangxiaoming/Documents/baidu/yy-cocos-giftplayer/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:198:30)
    at throwPluginError (/Users/liangxiaoming/Documents/baidu/yy-cocos-giftplayer/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:21718:12)
    at Object.error (/Users/liangxiaoming/Documents/baidu/yy-cocos-giftplayer/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:22672:20)
    at Object.error (/Users/liangxiaoming/Documents/baidu/yy-cocos-giftplayer/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:21895:42)
    at Object.transform (/Users/liangxiaoming/Documents/baidu/yy-cocos-giftplayer/node_modules/.pnpm/tsup@6.3.0/node_modules/tsup/dist/rollup.js:7217:20)
    at /Users/liangxiaoming/Documents/baidu/yy-cocos-giftplayer/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/shared/rollup.js:22879:40
DTS Build error
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by doerme** [comment]
change the code
```typescript
import Player, {IPlayerOption} from './player'
export const initPlayer = (op: IPlayerOption) => {
    new Player(op)
}
```
to
```typescript
import Player from './player'
import { IPlayerOption } from './types'
export const initPlayer = (op: IPlayerOption) => {
    new Player(op)
}
```
that is work!!

I guess tsup dts currently has a bug in handling import statements
