### ISSUE TITLE
TypeError: ts2.isNamedTupleMember is not a function

### ISSUE THREAD

**Issue by milahu** [egoist/tsup#808]
dts throws TypeError when typescript is not installed

the error message could be more friendly

```
npx tsup src/index.ts --format cjs,esm --dts 

CLI Building entry: src/index.ts
CLI Using tsconfig: tsconfig.json
CLI tsup v6.5.0
CLI Target: esnext
CJS Build start
ESM Build start
ESM dist/index.js 84.52 KB
ESM ⚡️ Build success in 637ms
CJS dist/index.cjs 85.36 KB
CJS ⚡️ Build success in 640ms
DTS Build start
TypeError: ts2.isNamedTupleMember is not a function
    at DeclarationScope.convertTypeNode (node_modules/.pnpm/tsup@6.5.0/node_modules/tsup/dist/rollup.js:6738:17)
    at DeclarationScope.convertMembers (node_modules/.pnpm/tsup@6.5.0/node_modules/tsup/dist/rollup.js:6692:18)
    at Transformer.convertClassOrInterfaceDeclaration (node_modules/.pnpm/tsup@6.5.0/node_modules/tsup/dist/rollup.js:7001:15)
    at Transformer.convertStatement (node_modules/.pnpm/tsup@6.5.0/node_modules/tsup/dist/rollup.js:6942:23)
    at new Transformer (node_modules/.pnpm/tsup@6.5.0/node_modules/tsup/dist/rollup.js:6899:16)
    at convert (node_modules/.pnpm/tsup@6.5.0/node_modules/tsup/dist/rollup.js:6890:27)
    at Object.transform (node_modules/.pnpm/tsup@6.5.0/node_modules/tsup/dist/rollup.js:7165:29)
    at transformFile (node_modules/.pnpm/tsup@6.5.0/node_modules/tsup/dist/rollup.js:7255:46)
    at Object.writeFile (node_modules/.pnpm/tsup@6.5.0/node_modules/tsup/dist/rollup.js:7278:27)
    at Object.writeFile (node_modules/.pnpm/typescript@3.9.10/node_modules/typescript/lib/typescript.js:16631:14)
Error: error occured in dts build
    at Worker.<anonymous> (node_modules/.pnpm/tsup@6.5.0/node_modules/tsup/dist/index.js:2226:26)
    at Worker.emit (node:events:513:28)
    at MessagePort.<anonymous> (node:internal/worker:238:53)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:734:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
DTS Build error

```

**Comment by await-ovo** [comment]
When typescript is not installed, I get the following error:

```
$ pnpm tsup
CLI Building entry: ./index.ts
CLI Using tsconfig: tsconfig.json
CLI tsup v6.5.0
CLI Using tsup config: /test/test-tsup-ts/tsup.config.ts
CLI Target: node14
CLI Cleaning output folder
CJS Build start
CJS dist/index.js 0 B
CJS ⚡️ Build success in 9ms

node:internal/event_target:912
  process.nextTick(() => { throw err; });
                           ^
Error: Cannot find module 'typescript'
Require stack:
- /node_modules/.pnpm/tsup@6.5.0/node_modules/tsup/dist/rollup.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/test/test-tsup-ts/node_modules/.pnpm/tsup@6.5.0/node_modules/tsup/dist/rollup.js:7317:19)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
Emitted 'error' event on Worker instance at:
    at Worker.[kOnErrorMessage] (node:internal/worker:289:10)
    at Worker.[kOnMessage] (node:internal/worker:300:37)
    at MessagePort.<anonymous> (node:internal/worker:201:57)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:643:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/test/test-tsup-ts/node_modules/.pnpm/tsup@6.5.0/node_modules/tsup/dist/rollup.js'
  ]
}
```

Compared with the information you provided, it looks more clearer, could you provide a repo to reproduce the problem you reported on your side?

Also, tsup itself does a[ check for missing typescript](https://github.com/egoist/tsup/blob/dev/src/rollup.ts#L262), but it doesn't seem to work, so this may be a bug ~

**Comment by milahu** [comment]
thanks, the problem in my case is: typescript is installed globally

```
tsc --version 
Version 4.7.0-dev.20220408

```
