### ISSUE TITLE
Error: Cannot find module 'node:path'

### ISSUE THREAD

**Issue by P1K3N** [egoist/tsup#825]
Hi! 
I'm trying to use tsup in my project but I receive the current error message when I try to build the project:

Error: Cannot find module 'node:path'
Require stack:
- /Users/bernardo.rodrigues/Documents/service/node_modules/rollup/dist/shared/rollup.js
- /Users/bernardo.rodrigues/Documents/service/node_modules/rollup/dist/rollup.js
- /Users/bernardo.rodrigues/Documents/service/node_modules/tsup/dist/index.js
- /Users/bernardo.rodrigues/Documents/service/node_modules/tsup/dist/chunk-PDM6VDW3.js
- /Users/bernardo.rodrigues/Documents/service/node_modules/tsup/dist/cli-default.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/bernardo.rodrigues/Documents/service/node_modules/rollup/dist/shared/rollup.js:12:19)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rl-rewards-service@0.0.1 build: `tsup src/index.ts`
npm ERR! Exit status 1

I'm running Nodejs v14 is this a problem? I couldn't find the minimum requirements to use the package 

  "engines": {
    "node": ">=14.17.0",
    "npm": "~6.14.13"
  },

**Comment by rayzr522** [comment]
the issue is that `node:path` wasn't available until v14.18:
![image](https://user-images.githubusercontent.com/15263431/218243756-50b5b22d-1886-4a8d-81d1-63a91f16a4b5.png)
([source](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V14.md#14.18.0))



but you're on v14.*17*. [rollup's `package.json`](https://github.com/rollup/rollup/blob/f125345413ea686003fb4f4c650a79c321372d45/package.json#L156) actually does indicate this requirement:
![image](https://user-images.githubusercontent.com/15263431/218243780-6df010b2-b35b-4612-bfc4-b55778e2a1b3.png)

so upgrading to the latest node v14 should fix your problem, but at the same time I recommend you actually upgrade to the current node lts (v18 as of writing this), as v14 is about to hit EOL:
![image](https://user-images.githubusercontent.com/15263431/218243812-e1a36548-1b3b-4255-935e-a0b1587c4bda.png)
([source](https://github.com/nodejs/Release))
