### ISSUE TITLE
`DTS Build failed` - undefined in reading `getFullText`

### ISSUE THREAD

**Issue by giorgiabosello** [egoist/tsup#860]
`TypeError: Cannot read properties of undefined (reading 'getFullText')` after upgrading to Typescript 5.0.

Currently using latest tsup version (6.7.0). 

Failing here, line 7415: `source` is undefined.
_node_modules/.pnpm/tsup@6.7.0/node_modules/tsup/dist/rollup.js_

![image](https://user-images.githubusercontent.com/9432544/226869188-b4e8f1f1-b8f1-4826-9cc8-1b54a9071dde.png)

**Comment by GiraffeCowGoat** [comment]
[tsup-860.zip](https://github.com/egoist/tsup/files/11073747/tsup-860.zip)

`npm run build1` # Run typescript and babel; works as expected
`npm run build2` # Run tsup; returns a DTS build error

```
TypeError: Cannot read properties of undefined (reading 'getFullText')
    at getModule (/Users/matt/Projects/tsup-860/src-js/node_modules/tsup/dist/rollup.js:7415:24)
    at generateDtsFromTs (/Users/matt/Projects/tsup-860/src-js/node_modules/tsup/dist/rollup.js:7479:29)
    at /Users/matt/Projects/tsup-860/src-js/node_modules/tsup/dist/rollup.js:7505:59
    at _nullishCoalesce (/Users/matt/Projects/tsup-860/src-js/node_modules/tsup/dist/rollup.js:1:198)
    at Object.transform (/Users/matt/Projects/tsup-860/src-js/node_modules/tsup/dist/rollup.js:7505:18)
    at /Users/matt/Projects/tsup-860/src-js/node_modules/rollup/dist/shared/rollup.js:24841:40
Error: error occured in dts build
    at Worker.<anonymous> (/Users/matt/Projects/tsup-860/src-js/node_modules/tsup/dist/index.js:2281:26)
    at Worker.emit (node:events:527:28)
    at MessagePort.<anonymous> (node:internal/worker:232:53)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:643:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
DTS Build error
```


Let me know if you need any more

**Comment by await-ovo** [comment]
Hi @GiraffeCowGoat, I have a little doubt as why you need to generate the type when bundling the `.js` file(this only seems to get `any` type)?

But anyway, setting `compilerOptions.allowJs: true` in `tsconfig.json` will avoid the error you got above.

**Comment by giorgiabosello** [comment]
Allowing JS risolved the issue, thank you @await-ovo and @GiraffeCowGoat .
