### ISSUE TITLE
--dts fails with typescript cli error

### ISSUE THREAD

**Issue by paulsmithkc** [egoist/tsup#884]
When trying to compile the type definition files for my library using the `tsup --dts` command, I am seeing the error shown below.

```
error TS5074: Option '--incremental' can only be specified using tsconfig, emitting to single file or when option '--tsBuildInfoFile' is specified.

Error: error occured in dts build
    at Worker.<anonymous> (D:\projects\express-packages\node_modules\tsup\dist\index.js:2281:26)
    at Worker.emit (node:events:513:28)
    at MessagePort.<anonymous> (node:internal/worker:233:53)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:694:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
DTS Build error
RollupError: Failed to compile. Check the logs above.
    at error (D:\projects\express-packages\node_modules\rollup\dist\shared\rollup.js:274:30)
    at Object.error (D:\projects\express-packages\node_modules\rollup\dist\shared\rollup.js:24694:20)
    at Object.error (D:\projects\express-packages\node_modules\rollup\dist\shared\rollup.js:23888:42)
    at generateDtsFromTs (D:\projects\express-packages\node_modules\tsup\dist\rollup.js:7498:22)
    at D:\projects\express-packages\node_modules\tsup\dist\rollup.js:7505:59
    at _nullishCoalesce (D:\projects\express-packages\node_modules\tsup\dist\rollup.js:1:198)
    at Object.transform (D:\projects\express-packages\node_modules\tsup\dist\rollup.js:7505:18)
    at D:\projects\express-packages\node_modules\rollup\dist\shared\rollup.js:24893:40
```

**Comment by vaynevayne** [comment]
same issue, Has some to disable type check?

**Comment by benjidotsh** [comment]
Not sure how helpful this is, but I got it working after setting `compilerOptions.incremental` to false in my `tsconfig.json`

**Comment by rjborba** [comment]
> Not sure how helpful this is, but I got it working after setting `compilerOptions.incremental` to false in my `tsconfig.json`

Same for me! Thanks!
