### ISSUE TITLE
dts generation crashes at MagicString.update

### ISSUE THREAD

**Issue by IlyaSemenov** [egoist/tsup#886]
With the latest sub-deps of tsup, it fails to generate DTS on a very minimal example:

```ts
export function square(x: number) {
  return x * x
}
```

```ts
import { defineConfig } from "tsup"

export default defineConfig({
    clean: true,
    entry: ["test.ts"],
    format: ["esm"],
    dts: true,
})
```

Output:

```
❯ pnpm tsup
CLI Building entry: index.ts
CLI tsup v6.7.0
CLI Using tsup config: /home/projects/node-srpwmo/tsup.config.ts
CLI Target: node14
CLI Cleaning output folder
ESM Build start
ESM dist/index.mjs 72.00 B
ESM ⚡️ Build success in 48ms
DTS Build start
Error: Cannot overwrite a zero-length range – use appendLeft or prependRight instead
    at MagicString.update (file:///home/projects/node-srpwmo/node_modules/.pnpm/rollup@3.20.5/node_modules/rollup/dist/shared/rollup.js:2142:10)
    at MagicString.overwrite (file:///home/projects/node-srpwmo/node_modules/.pnpm/rollup@3.20.5/node_modules/rollup/dist/shared/rollup.js:2131:15)
    at Identifier.render (file:///home/projects/node-srpwmo/node_modules/.pnpm/rollup@3.20.5/node_modules/rollup/dist/shared/rollup.js:8762:22)
    at AssignmentPattern.render (file:///home/projects/node-srpwmo/node_modules/.pnpm/rollup@3.20.5/node_modules/rollup/dist/shared/rollup.js:9439:19)
    at FunctionDeclaration.render (file:///home/projects/node-srpwmo/node_modules/.pnpm/rollup@3.20.5/node_modules/rollup/dist/shared/rollup.js:6346:28)
    at renderStatementList (file:///home/projects/node-srpwmo/node_modules/.pnpm/rollup@3.20.5/node_modules/rollup/dist/shared/rollup.js:8913:35)
    at Program.render (file:///home/projects/node-srpwmo/node_modules/.pnpm/rollup@3.20.5/node_modules/rollup/dist/shared/rollup.js:12199:13)
    at Module.render (file:///home/projects/node-srpwmo/node_modules/.pnpm/rollup@3.20.5/node_modules/rollup/dist/shared/rollup.js:14105:18)
    at Chunk.renderModules (file:///home/projects/node-srpwmo/node_modules/.pnpm/rollup@3.20.5/node_modules/rollup/dist/shared/rollup.js:16554:41)
    at Chunk.render (file:///home/projects/node-srpwmo/node_modules/.pnpm/rollup@3.20.5/node_modules/rollup/dist/shared/rollup.js:16062:111)
Error: error occured in dts build
    at Worker.eval (file:///home/projects/node-srpwmo/node_modules/.pnpm/tsup@6.7.0_typescript@5.0.4/node_modules/tsup/dist/index.js:2281:26)
    at EventEmitter.emit (https://nodesrpwmo-cjxv.w-credentialless.staticblitz.com/blitz.c8358679.js:35:156830)
    at _0x3cbdc4.<anonymous> (https://nodesrpwmo-cjxv.w-credentialless.staticblitz.com/blitz.c8358679.js:35:934951)
    at [nodejs.internal.kHybridDispatch] (https://nodesrpwmo-cjxv.w-credentialless.staticblitz.com/blitz.c8358679.js:35:413600)
    at t.emitMessage (https://nodesrpwmo-cjxv.w-credentialless.staticblitz.com/blitz.c8358679.js:35:1134926)
    at <computed>._source.<computed>.<computed> (https://nodesrpwmo-cjxv.w-credentialless.staticblitz.com/blitz.c8358679.js:44:83400)
DTS Build error
```

Reproduction: https://stackblitz.com/edit/node-srpwmo (run: `pnpm tsup`)

It used to work with the set of deps as of Mar 26 (I can attach one if there is a need).

**Comment by strawhat-dev** [comment]
As evident by the error message, this is being caused by the newest rollup update that was released around 3 hours ago. Rolling rollup back to version 3.20.4 works as before. You may override the version tsup is using by adding the following to your package.json and reinstalling (using pnpm):
```json
  "pnpm": {
    "overrides": {
      "tsup>rollup": "3.20.4"
    }
  },
```

**Comment by IlyaSemenov** [comment]
Closing as this has been resolved upstream.
