### ISSUE TITLE
DTS doesn't support hashbang

### ISSUE THREAD

**Issue by AntoineKM** [egoist/tsup#910]
In the documentation it is stated that:
![image](https://github.com/egoist/tsup/assets/54948363/b6cb9cfe-4cd0-44a9-8241-e4be682add91)

So I followed your example with `src/cli.ts`, then everything works fine without the DTS build.

As mentioned in [my actions fails](https://github.com/AntoineKM/dixt/actions/runs/5038219113/jobs/9035557486):
```sh
DTS Build start
Error: Syntax not yet supported

  1 | import * as yargs from "yargs";
> 2 | #!/usr/bin/env node
    |  ^^^^^^^^^^^^^
  3 | declare const cli: yargs.Argv<{}>;
  4 | export default cli;
  5 |
    at Transformer.convertStatement (/home/runner/work/dixt/dixt/node_modules/.pnpm/tsup@6.7.0_typescript@4.9.3/node_modules/tsup/dist/rollup.js:7147:17)
    at new Transformer (/home/runner/work/dixt/dixt/node_modules/.pnpm/tsup@6.7.0_typescript@4.9.3/node_modules/tsup/dist/rollup.js:7084:16)
    at convert (/home/runner/work/dixt/dixt/node_modules/.pnpm/tsup@6.7.0_typescript@4.9.3/node_modules/tsup/dist/rollup.js:7075:27)
    at Object.transform (/home/runner/work/dixt/dixt/node_modules/.pnpm/tsup@6.7.0_typescript@4.9.3/node_modules/tsup/dist/rollup.js:7350:29)
    at Object.writeFile (/home/runner/work/dixt/dixt/node_modules/.pnpm/tsup@6.7.0_typescript@4.9.3/node_modules/tsup/dist/rollup.js:7488:55)
    at Object.writeFile (/home/runner/work/dixt/dixt/node_modules/.pnpm/typescript@4.9.3/node_modules/typescript/lib/typescript.js:18685:14)
    at printSourceFileOrBundle (/home/runner/work/dixt/dixt/node_modules/.pnpm/typescript@4.9.3/node_modules/typescript/lib/typescript.js:113053:16)
    at emitDeclarationFileOrBundle (/home/runner/work/dixt/dixt/node_modules/.pnpm/typescript@4.9.3/node_modules/typescript/lib/typescript.js:112985:17)
    at emitSourceFileOrBundle (/home/runner/work/dixt/dixt/node_modules/.pnpm/typescript@4.9.3/node_modules/typescript/lib/typescript.js:112853:13)
    at forEachEmittedFile (/home/runner/work/dixt/dixt/node_modules/.pnpm/typescript@4.9.3/node_modules/typescript/lib/typescript.js:112591:34)
Error: error occured in dts build
    at Worker.<anonymous> (/home/runner/work/dixt/dixt/node_modules/.pnpm/tsup@6.7.0_typescript@4.9.3/node_modules/tsup/dist/index.js:2281:26)
    at Worker.emit (node:events:513:28)
    at MessagePort.<anonymous> (node:internal/worker:236:53)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:736:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
DTS Build error
 ELIFECYCLE  Command failed with exit code 1.
ERROR: command finished with error: command (/home/runner/work/dixt/dixt/packages/dixt) pnpm run build exited (1)
```

Indeed, it seems that it does not support hasbangs!

- [ ] https://github.com/Swatinem/rollup-plugin-dts/issues/265

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/egoist) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/egoist/tsup/issues/910">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/egoist/tsup/issues/910/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/egoist/tsup/issues/910/pledge.svg">
</picture>
</a>

**Comment by AntoineKM** [comment]
Possible but weird workaround:
Replace `import yargs from "yargs/yargs";` by `const yargs = require("yargs/yargs");`but you will not be able to access yargs types anymore

**Comment by AntoineKM** [comment]
Workaround here: https://github.com/AntoineKM/dixt/pull/39/commits/fd56ac9737c76215c82341f7f49c87959eb1fb90
