### ISSUE TITLE
Upgrade to esbuild 0.18

### ISSUE THREAD

**Issue by ndelangen** [egoist/tsup#923]
I'm trying to upgrade storybook to esbuild 0.18, but it seems tsup is not yet on 0.18 and it seems like it's conflicting?

PR:
https://github.com/storybookjs/storybook/pull/23017

CI:
https://app.circleci.com/pipelines/github/storybookjs/storybook/51851/workflows/fb87aa28-faf5-47cf-87ff-274987eb1c05/jobs/540940

LOG:
```
> nx run @storybook/vue3:prep --reset --optimized

RollupError: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (/tmp/storybook/scripts/node_modules/rollup/dist/shared/rollup.js:284:30)
    at Module.error (/tmp/storybook/scripts/node_modules/rollup/dist/shared/rollup.js:14009:16)
    at Module.tryParse (/tmp/storybook/scripts/node_modules/rollup/dist/shared/rollup.js:14730:25)
    at Module.setSource (/tmp/storybook/scripts/node_modules/rollup/dist/shared/rollup.js:14332:39)
    at ModuleLoader.addModuleSource (/tmp/storybook/scripts/node_modules/rollup/dist/shared/rollup.js:24328:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I've been tracing what's causing this failure and was able to get a bit more information out:
```
{
  cause: SyntaxError: Unexpected token (20:22447)
      at Object.pp$4.raise (/Users/me/Projects/Storybook/core/scripts/node_modules/rollup/dist/shared/rollup.js:21736:13)
      at Object.pp$9.unexpected (/Users/me/Projects/Storybook/core/scripts/node_modules/rollup/dist/shared/rollup.js:19035:8)
      at Object.pp$5.parseIdent (/Users/me/Projects/Storybook/core/scripts/node_modules/rollup/dist/shared/rollup.js:21667:10)
      at Object.pp$5.parsePropertyName (/Users/me/Projects/Storybook/core/scripts/node_modules/rollup/dist/shared/rollup.js:21470:109)
      at Object.pp$5.parseProperty (/Users/me/Projects/Storybook/core/scripts/node_modules/rollup/dist/shared/rollup.js:21396:8)
      at Object.pp$5.parseObj (/Users/me/Projects/Storybook/core/scripts/node_modules/rollup/dist/shared/rollup.js:21359:21)
      at Object.pp$5.parseExprAtom (/Users/me/Projects/Storybook/core/scripts/node_modules/rollup/dist/shared/rollup.js:21094:17)
      at Object.pp$5.parseExprSubscripts (/Users/me/Projects/Storybook/core/scripts/node_modules/rollup/dist/shared/rollup.js:20910:19)
      at Object.pp$5.parseMaybeUnary (/Users/me/Projects/Storybook/core/scripts/node_modules/rollup/dist/shared/rollup.js:20876:17)
      at Object.pp$5.parseExprOps (/Users/me/Projects/Storybook/core/scripts/node_modules/rollup/dist/shared/rollup.js:20803:19) {
    pos: 146699,
    loc: Position { line: 20, column: 22447 },
    raisedAt: 146700
  },
  code: 'PARSE_ERROR',
  id: '/Users/me/Projects/Storybook/core/code/renderers/vue3/dist/config.mjs',
  message: 'Unexpected token (Note that you need plugins to import files that are not JavaScript)'
}
RollupError: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (/Users/me/Projects/Storybook/core/scripts/node_modules/rollup/dist/shared/rollup.js:284:30)
    at Module.error (/Users/me/Projects/Storybook/core/scripts/node_modules/rollup/dist/shared/rollup.js:14009:16)
    at Module.tryParse (/Users/me/Projects/Storybook/core/scripts/node_modules/rollup/dist/shared/rollup.js:14732:25)
    at Module.setSource (/Users/me/Projects/Storybook/core/scripts/node_modules/rollup/dist/shared/rollup.js:14332:39)
    at ModuleLoader.addModuleSource (/Users/me/Projects/Storybook/core/scripts/node_modules/rollup/dist/shared/rollup.js:24332:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I was able to print the `this.input` rollup is interacting on, and found it's breaking here:
![Screenshot 2023-06-12 at 09 49 55](https://github.com/egoist/tsup/assets/3070389/4026b33f-408e-4cf8-8283-7bf49483e109)

which if i don't optimize whitespace looks like:
![Screenshot 2023-06-12 at 10 01 53](https://github.com/egoist/tsup/assets/3070389/97ad71ec-61df-4e48-8889-4bc6b752b211)

And this function seems to be used inside `runInContext` of `lodash`.. what a rabbit hole.

I'm hoping upgrading tsup will just resolve some version conflict..

**Comment by ndelangen** [comment]
Ok, after digging deeper and deeper, I found a solution.

I'll close this issue, but would still appreciate a bump of dependencies including `esbuild` let me know if I can help @egoist.
