### ISSUE TITLE
TSConfig Bases Cannot Be Loaded By load-tsconfig

### ISSUE THREAD

**Issue by bestickley** [egoist/tsup#973]
Hi, when I try to use tsup I get the error:

```bash
Error: Cannot find module '@tsconfig/strictest'
Require stack:
- /Users/stickb/Code/green-boost/node_modules/.pnpm/load-tsconfig@0.2.5/node_modules/load-tsconfig/dist/index.cjs
- /Users/stickb/Code/green-boost/node_modules/.pnpm/bundle-require@4.0.1_esbuild@0.18.11/node_modules/bundle-require/dist/index.cjs
- /Users/stickb/Code/green-boost/node_modules/.pnpm/tsup@7.2.0_typescript@5.1.6/node_modules/tsup/dist/chunk-52KWB5QB.js
- /Users/stickb/Code/green-boost/node_modules/.pnpm/tsup@7.2.0_typescript@5.1.6/node_modules/tsup/dist/index.js
- /Users/stickb/Code/green-boost/node_modules/.pnpm/tsup@7.2.0_typescript@5.1.6/node_modules/tsup/dist/chunk-E33JV7SQ.js
- /Users/stickb/Code/green-boost/node_modules/.pnpm/tsup@7.2.0_typescript@5.1.6/node_modules/tsup/dist/cli-default.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Function.resolve (node:internal/modules/cjs/helpers:116:19)
    at resolveTsConfigFromExtends (/Users/stickb/Code/green-boost/node_modules/.pnpm/load-tsconfig@0.2.5/node_modules/load-tsconfig/dist/index.cjs:163:18)
    at loadTsConfigInternal (/Users/stickb/Code/green-boost/node_modules/.pnpm/load-tsconfig@0.2.5/node_modules/load-tsconfig/dist/index.cjs:169:26)
    at loadTsConfigInternal (/Users/stickb/Code/green-boost/node_modules/.pnpm/load-tsconfig@0.2.5/node_modules/load-tsconfig/dist/index.cjs:185:28)
    at loadTsConfig (/Users/stickb/Code/green-boost/node_modules/.pnpm/load-tsconfig@0.2.5/node_modules/load-tsconfig/dist/index.cjs:209:35)
    at /Users/stickb/Code/green-boost/node_modules/.pnpm/bundle-require@4.0.1_esbuild@0.18.11/node_modules/bundle-require/dist/index.cjs:173:60
    at new Promise (<anonymous>)
    at bundleRequire (/Users/stickb/Code/green-boost/node_modules/.pnpm/bundle-require@4.0.1_esbuild@0.18.11/node_modules/bundle-require/dist/index.cjs:165:10)
    at loadTsupConfig (/Users/stickb/Code/green-boost/node_modules/.pnpm/tsup@7.2.0_typescript@5.1.6/node_modules/tsup/dist/chunk-52KWB5QB.js:1361:55)
 ELIFECYCLE  Command failed with exit code 1.
```

It looks like there is a PR [here](https://github.com/egoist/load-tsconfig/pull/24) that will fix the issue but want to document here for others to find.

**Comment by mjvestal** [comment]
Is there a work around for this issue?
